# Generated by Django 2.1.7 on 2019-05-19 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_planning', '0010_auto_20190518_1535'),
        ('student_management', '0003_sex_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEctsMakrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EctsMark', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllMarksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(100)])),
                ('ects_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.AllEctsMakrs')),
            ],
        ),
        migrations.CreateModel(
            name='AllNationalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_mark_ukr', models.CharField(max_length=20, unique=True)),
                ('national_mark_rus', models.CharField(max_length=10, unique=True)),
                ('national_mark_ukr_shotr', models.CharField(max_length=20, unique=True)),
                ('national_mark_rus_short', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_year', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_hvostovke', models.BooleanField(default=False)),
                ('educational_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.EducationalYears')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.AllMarksList')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SyllabusesPrograms')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Students')),
            ],
        ),
        migrations.AddField(
            model_name='allmarkslist',
            name='national_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.AllNationalMarks'),
        ),
    ]
