# Generated by Django 2.1.7 on 2019-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0010_auto_20190518_1535'),
        ('student_management', '0003_sex_short_name'),
        ('marks_system', '0002_auto_20190519_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnationalmarks',
            name='national_mark_rus',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='allnationalmarks',
            name='national_mark_rus_short',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='allnationalmarks',
            name='national_mark_ukr',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='allnationalmarks',
            name='national_mark_ukr_short',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentsmarks',
            unique_together={('student', 'program', 'educational_year')},
        ),
    ]
