# Generated by Django 2.1.7 on 2019-05-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0003_auto_20190519_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEducationalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.EducationalYears')),
            ],
        ),
    ]
