# Generated by Django 2.1.7 on 2019-05-22 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20190521_0222'),
        ('marks_system', '0004_currenteducationalyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesForExtraMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_extra_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('few', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsExtraMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1)),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.ActivitiesForExtraMarks')),
                ('educational_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.EducationalYears')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Students')),
            ],
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allmarkslist',
            name='mark',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='activitiesforextramarks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.ActivityCategories'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsextramarks',
            unique_together={('student', 'semester', 'educational_year', 'activity')},
        ),
    ]
