# Generated by Django 2.1.7 on 2019-05-22 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0005_auto_20190522_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsextramarks',
            name='date',
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 21, 8, 39, 530823, tzinfo=utc)),
        ),
    ]
