# Generated by Django 2.1.7 on 2019-05-23 00:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0006_auto_20190523_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsextramarks',
            options={'ordering': ['semester']},
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 0, 42, 3, 56834, tzinfo=utc)),
        ),
    ]
