# Generated by Django 2.1.7 on 2019-05-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Departments')),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.EducationalLevels')),
            ],
        ),
        migrations.CreateModel(
            name='FacultiesAndInstututes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FucultyInstituteSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_insitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.FacultiesAndInstututes')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fucultyinstitutespecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Specialties'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='faculty_insitute_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.FucultyInstituteSpecialty'),
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty_insitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.FacultiesAndInstututes'),
        ),
        migrations.AlterUniqueTogether(
            name='fucultyinstitutespecialty',
            unique_together={('faculty_insitute', 'specialty')},
        ),
    ]
