# Generated by Django 2.1.7 on 2019-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultiesandinstututes',
            name='specialty',
            field=models.ManyToManyField(through='university_structure.FucultyInstituteSpecialty', to='university_structure.Specialties'),
        ),
    ]
