# Generated by Django 2.1.7 on 2019-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0002_facultiesandinstututes_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='cypher',
            field=models.PositiveIntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='cypher',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultiesandinstututes',
            name='cypher',
            field=models.PositiveIntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialties',
            name='cypher',
            field=models.PositiveIntegerField(default=1111),
            preserve_default=False,
        ),
    ]
