# Generated by Django 2.1.7 on 2019-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0004_auto_20190511_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='cypher',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='educationalprograms',
            name='cypher',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facultiesandinstututes',
            name='cypher',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='cypher',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
