# Generated by Django 2.1.7 on 2019-05-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_structure', '0004_auto_20190511_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cypher', models.CharField(max_length=50)),
                ('year_of_approval', models.DateField()),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.EducationalPrograms')),
            ],
            options={
                'ordering': ['cypher'],
            },
        ),
    ]
