# Generated by Django 2.1.7 on 2019-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0002_auto_20190511_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuses',
            name='year_of_approval',
            field=models.DateField(),
        ),
    ]
