# Generated by Django 2.1.7 on 2019-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0004_auto_20190511_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuses',
            name='cypher',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
