# Generated by Django 2.1.7 on 2019-05-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0006_auto_20190512_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusesprograms',
            name='individual_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education_planning.IndividualTasks'),
            preserve_default=False,
        ),
    ]
