# Generated by Django 2.1.7 on 2019-05-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0007_syllabusesprograms_individual_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndTaskSyllProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.IndividualTasks')),
            ],
        ),
        migrations.RemoveField(
            model_name='syllabusesprograms',
            name='individual_task',
        ),
        migrations.AddField(
            model_name='indtasksyllprog',
            name='syllabus_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SyllabusesPrograms', unique=True),
        ),
    ]
