# Generated by Django 2.1.7 on 2019-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0008_auto_20190512_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabusesprogramsclassestypes',
            name='number_of_hours',
            field=models.IntegerField(null=True),
        ),
    ]
