# Generated by Django 2.1.7 on 2019-05-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0009_auto_20190513_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemControlSyllProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='semestercontroltypes',
            options={},
        ),
        migrations.RemoveField(
            model_name='syllabusesprograms',
            name='semester_control_type',
        ),
        migrations.AlterField(
            model_name='syllabusesprograms',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
        migrations.AddField(
            model_name='semcontrolsyllprog',
            name='semester_control_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SemesterControlTypes'),
        ),
        migrations.AddField(
            model_name='semcontrolsyllprog',
            name='syllabus_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SyllabusesPrograms', unique=True),
        ),
    ]
