# Generated by Django 2.1.7 on 2019-05-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planning', '0010_auto_20190518_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indtasksyllprog',
            name='syllabus_program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SyllabusesPrograms'),
        ),
        migrations.AlterField(
            model_name='semcontrolsyllprog',
            name='syllabus_program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education_planning.SyllabusesPrograms'),
        ),
        migrations.AlterField(
            model_name='syllabuses',
            name='year_of_approval',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='year'),
        ),
    ]
