# Generated by Django 2.1.7 on 2019-05-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_structure', '0005_auto_20190511_2333'),
        ('education_planning', '0010_auto_20190518_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star_year', models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, max_length=4, verbose_name='year')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Departments')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.EducationalPrograms')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planning.Syllabuses')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birdth', models.DateField()),
                ('finance_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.FinanceSources')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Groups')),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.Sex')),
            ],
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Groups'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Students'),
        ),
        migrations.AddField(
            model_name='financehistory',
            name='finance_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.FinanceSources'),
        ),
        migrations.AddField(
            model_name='financehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Students'),
        ),
        migrations.AlterUniqueTogether(
            name='grouphistory',
            unique_together={('student', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='financehistory',
            unique_together={('student', 'start_date')},
        ),
    ]
