# Generated by Django 2.1.7 on 2019-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20190518_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='short_name',
            field=models.CharField(default='h', max_length=1),
        ),
    ]
