# Generated by Django 2.1.7 on 2019-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_sex_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='start_year',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='year'),
        ),
    ]
