# Generated by Django 2.1.7 on 2019-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20190521_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birdth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
